version: '3'

services:
  airflow:
    build:
      context: ../
      dockerfile: docker/airflow/Dockerfile
    volumes:
      - ./src:/opt/airflow/src
      - ./docker/airflow/dags:/opt/airflow/dags
    ports:
      - "8080:8080"
    depends_on:
      - kafka

  kafka:
    build:
      context: ../
      dockerfile: docker/kafka/Dockerfile
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper

  fastapi:
    build:
      context: ../
      dockerfile: docker/fastapi/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - kafka